version: 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo Installing dependencies...”
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo “Running tests...”
          npm run test
          
  publish:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            docker build -t test-image .
            docker tag test-image afawafa/education-space:latest
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push afawafa/education-space:latest

  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: afawafa/education-space
      - docker/push:
          image: afawafa/education-space
  deploy:
    docker:
        - image: cimg/node:16.10
    steps:
        - setup_remote_docker      
        - heroku/install
        - checkout
        - run:
            name: Heroku Container Push
            command: | 
                heroku container:login
                heroku container:push web -a justin-su-devops
                heroku container:release web -a justin-su-devops

workflows:
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - main

  build-and-push-and-deploy:
      jobs:
        - build:
            filters:
              branches:
                only:
                  - main
        - test:
            requires:
              - build
            filters:
              branches:
                only:
                  - main
        - build-and-push:
            requires:
              - test
            filters:
              tags:
                only: /^v[0-9]+(\.[0-9]+)*$/
        - deploy:
            requires:
              - build-and-push
            filters:
              tags:
                only: /^v[0-9]+(\.[0-9]+)*$/
